version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: receipt
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwe123

  app:
    container_name: fastapi_receipts
    restart: always
    build: app
    ports:
      - "8000:8000"
    depends_on:
      - db